name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Unit Tests
        run: yarn test

      - name: E2E Tests
        run: yarn start & node_modules/.bin/wait-on http://localhost:3000
        uses: cypress-io/github-action@v1

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy with ZEIT/Vercel
        run: now --token=$ZEIT_TOKEN --prod --confirm
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
