name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Unit Tests
        run: yarn test

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Lateral API Key
        run: now --token=$ZEIT_TOKEN secrets add lateral-key $LATERAL_TOKEN
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}

      - name: Deploy with ZEIT/Vercel
        run: now --token=$ZEIT_TOKEN --prod --confirm
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          LATERAL_TOKEN: ${{ secrets.LATERAL_TOKEN }}
